kind: Service
apiVersion: v1
metadata:
  name: hello-app
  namespace: hello-app
spec:
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hello-app
